databases:
  - name: postgres
    ipAllowList: []

services:
  - type: web
    name: rails
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
  - type: redis
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction

# databases:
#   - name: render-deploy
#     databaseName: render-deploy
#     user: render-deploy
#
# services:
#   - type: web
#     name: render-deploy
#     env: ruby
#     buildCommand: "./bin/render-build.sh"
#     startCommand: bundle exec rails s
#     envVars:
#       - key: DATABASE_URL
#         fromDatabase:
#           name: render-deploy
#           property: connectionString
#       - key: RAILS_MASTER_KEY
#         sync: false
